### ISSUE TITLE
Discuss New Wages/Prices system, Maybe with some very simple form of economic module

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#121]

**Comment by DarkTl** [comment]
Wages and stats/skills:

- We cannot bind wages to skills directly as long as they can be raised infinitely and are not limited by anything, it's a path to infinite wages.

- I believe wages should be based on character level and class. Class will give a base value (twice in the case of a single class), and every level will increase it a bit. 

When we try to include there stats or skills, we discourage players to train characters. Surprisingly, it leads to tricks when players decrease stats on purpose to make wages lower, they did it a lot during the alpha. I'm not saying it's a very bad thing, but it's a bit illogical when a pretty character wears ugly armor and expects less wage.

- We could invent an indirect system, when we somehow normalize skills before using them to calculate wages. But some classes focus on stats while others on skills, it might lead to huge wages imbalance. Another reason to not calculate wages based on them.

- To provide control over wages and not make them overwhelming and quickly increasing, we could make level ups manual, ie only with the permission of the player. This way if the player cannot afford to pay more yet, he can stop leveling the character until the situation will change. Such characters will not get any more exp until leveled up.

**Comment by DarkTl** [comment]
Customers-based jobs income:
- Every customer has a limited, random amount of gold based on his social level. I think we already have something like that, but I don't remember the details. The more reputation the building has (no matter what you do there), the more customers and with higher levels come.
- The more level of the customer, the higher skill is required to make him/her happy and part with gold. Since they also have more money at higher levels, it is worth it anyway.
- While skills determine how happy the customer will be after the service, thus how many willing to pay and how many reputation to give, stats will determine other things, like how many customers the character can serve (agility and constitution), whether customers like the character or not (ie tips), etc.

**Comment by XelaPy** [comment]
Moved to the forums...
