### ISSUE TITLE
Learning base spells

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#16]
- Update all NPCs that teach spells to work with a new system

**Comment by DarkTl** [comment]
I can easily make items for that. Especially for powerful spells that are supposed to be rare.

**Comment by Xela00** [comment]
That is one options for some spells. I feel however that some spells should be always available... Spells should also consume (a lot) moar MP then they do now.

**Comment by DarkTl** [comment]
Ok, do it for all ff-like spells. I'll make items for others.

Btw do we want to limit available spells with available elemental traits? Like no light spells without light trait, or maybe no light spells with darkness trait unless light is there as well?

**Comment by Xela00** [comment]
Yeap, that's a plan. Not just items, we should make events for it as well.

On the second issue, I do not particularly care. It's not that difficult to have it either way I think. Obviously allowing everyone to learn every spell is easier, they'll just suck at it. I think I should add an option to "unlearn" a spell. It's actually very easy to do since all of the spells are buttons in the GUI already.

**Comment by DarkTl** [comment]
Aaand I forgot again how to add spells via items because I never had a chance to do it before :dizzy_face:

**Comment by DarkTl** [comment]
Yeap, items for learning advanced spells are there. Of course we cannot afford to use unique icons in this case.
