### ISSUE TITLE
Strip Club and Brothel Upgrades and corresponding jobs

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#71]
To keep track of progress and break the task into smaller bits:

1) Clients:
- Are being supplied as a stream in random intervals.
- Have priorities (likes).
- Are generated on per building basis.
- For there favorites and become regulars while other are being generated. Amount of regulars is determined by building capacity and amount of worker.
- Manager can redirect clients and temporarily change their priorities.

2) Whore Job:
- Checks if there are rooms.
- Searches for a good match based on traits out of available workers.
- Takes one client (for now) max if there are workers available and runs the job.
- Manager bonuses.

3) Strip Club is a lot more complex:
- Clients are being sent in until club is at full capacity.
- Clients leave prematurely if there are no strippers.
- Clients tip the strippers they like.
- Clients stay at the club for longer if they are satisfied.
- Clients are expected to be served drinks and snacks. There is cashflow if they do for as long as there are servers.
- Servers keep generating cash on per client basis per x amount of discrete time units.
- Matron effects.

Other Tasks:
- Figure out if we can provide instances of clients and workers directly to SimPy so it will track it without modifications to it's classes.
- If the above is False, figure out if the best tracking system is to add it to SimPy or Building/Upgrade classes.
- First there is simulation of the base code, soon I will move it to work with buildings/upgrades directly.

**Comment by DarkTl** [comment]
Except obvious sex skills checks during jobs, other stats:
- charisma is important for everyone. From two chars with identical traits a customer will prefer the one with higher charisma. And there will be more tips during strip.
- character stat is important for strip job, since it requires a certain self confidence, and for servers in order to not be distracted by customers while working.
- constitution 
- for whores character stat could be used as another preference, ie some customers like 
temperamental ones and others don't.

**Comment by XelaPy** [comment]
Noted, I'll take it one thing at a time. Too many parameters for sorting may not be reasonable, we need to keep performance in mind.
