### ISSUE TITLE
Social levels?

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#72]
Ie how rich the character is, how well she lives, etc. I personally need it to determine background when you go to character's room, to find out how she reacts to certain gifts and giving money, how difficult it might be to hire her. 

On the other hand we can do it based on gold and character level, and code in a different way for slaves (slaves life conditions should be based on your decisions, not their gold), but another option is to use a system of social levels.

**Comment by XelaPy** [comment]
We've talked about this before, it's a very complicated topic, we need to make it as simple and at the same time as useful as possible. Lets think about it or start a discussion at pinkpetal to mirror this one.

**Comment by armegetton** [comment]
I personally would like having a "social level". But for the main character instead of gold/level check, wouldn't it be better if it were affected by what items you are wearing, and maybe thresholds for intelligence and charisma? (or maybe just the items)

that way, you could have events or checks for high "social level" as well as low "social level", to wear cheap clothes to maybe get into a shady area. just my thoughts.

and for the slaves it could be based on education levels (from taking classes or training) with bonuses from items.

**Comment by DarkTl** [comment]
Concept was created: http://www.pinkpetal.org/index.php?topic=3665
