### ISSUE TITLE
Add a way to call any specific image by Name to Girl.show()

### ISSUE THREAD

**Issue by XelaPy** [XelaPy/PyTFall#77]
- Should be VERY useful for events that require specific images from packs. Right now best workaround is to provide all of the tags and hope that there is only one image OR declare image using Ren'Py statement with the direct path, which is prolly less convenient.

**Comment by DarkTl** [comment]
Yup, I have to call images very carefully because of it. Thankfully, naruto characters don't have too many pictures, but when we'll do touhou stories for example, there will be problems with calling via tags for sure since those packs are much bigger.

**Comment by Xipomus** [comment]
Or create a quest tag. Q[number] so you can call it when neccessary.

**Comment by DarkTl** [comment]
I'm afraid in the case of big packs we should avoid forcing people to download them again. I honestly thought that these days everyone who owns a pc also has a decent internet connection at least at home, but surprisingly I was wrong, since there were people complaining about the size of our alpha a year ago.

So a special quest tag will mean that we have to create all events for the pack in advance in order to not retag and reupload it, forcing people to redownloading it.

**Comment by Xipomus** [comment]
And an extra "tag" in the girl xml? instead of on the picture it self.. like q11=picname.jpg?
