### ISSUE TITLE
Unusable items

### ISSUE THREAD

**Issue by DarkTl** [XelaPy/PyTFall#91]
Ie items that have a price, description, location, etc. But they don't do a thing, you can't consume or equip them. You only can transfer, buy or sell them. Our gems are supposed to be such items, for example.

I think they could be a part of miscs in order to not change gui, adding new categories there.

**Comment by MoreinAI** [comment]
For example, we have a diamond. In its properties set "Slot-> Loot, Type-> Treasure".
It turns out all items that you described above take it for treasures or other "Type" tags and instead of "Loot" put in "Misc"?
Now all items tagged "Loot - Treasure" can be seen only in the "All" filter.
It would be good to attach them to the "Misc" filters)

**Comment by DarkTl** [comment]
Yeap, we basically need to change all filters settings a bit to show loot slot items in miscs.

But there is another problem too, the game proposes you to equip loot items in gui. Nothing happens if you try it, but still it will be confusing, we need to disable equip option for them.
